import os
import time

print ("_______________________________________________________")
print()
print()
print()
print ("""\033[96m 
           
           | ░█████╗░███╗░░██╗██████╗░██████╗░██╗░█████╗░
           |  ██╔══██╗████╗░██║██╔══██╗██╔══██╗██║██╔══██╗
           |  ███████║██╔██╗██║██║░░██║██████╔╝██║██║░░██║
           |  ██╔══██║██║╚████║██║░░██║██╔══██╗██║██║░░██║
           |  ██║░░██║██║░╚███║██████╔╝██║░░██║██║╚█████╔╝
           |  ╚═╝░░╚═╝╚═╝░░╚══╝╚═════╝░╚═╝░░╚═╝╚═╝░╚════╝░
           |
           | ████████╗░██╗░░░░░░░██╗███████╗░█████╗░██╗░░██╗
           | ╚══██╔══╝░██║░░██╗░░██║██╔════╝██╔══██╗██║░██╔╝
           | ░░░██║░░░░╚██╗████╗██╔╝█████╗░░███████║█████═╝░
           | ░░░██║░░░░░████╔═████║░██╔══╝░░██╔══██║██╔═██╗░
           | ░░░██║░░░░░╚██╔╝░╚██╔╝░███████╗██║░░██║██║░╚██╗
           | ░░░╚═╝░░░░░░╚═╝░░░╚═╝░░╚══════╝╚═╝░░╚═╝╚═╝░░╚═╝""")
print("                        [*]  YOUTUBE : EUGENE TSU         ")
print()
print()
print()
print()
print()
print()
print()
print()
print("\033[96m      **MENU GAMES** ")
print()
print()
print()
print()
print("  _________________________")
print("  |   [*] MOBILE LEGENDS  |")
print()
print()
print("  |   [*] PUBG MOBILE         |")
print()
print()
print("  |   [*] CALL OF DUTY        |")
print("  _________________________")
print()
print()
print()
print()
print()
print()
print()
print()
input("\033[0m[*] Select Your Favorite Game :")
print()
print()
print()
print("\033[92m[*] Entering Menu FPS....")
time.sleep(1)
print("[*] Please wait...")
time.sleep(1)
print("[*] Please wait...")
time.sleep(1)
print("[*] Please wait...")
time.sleep(1)
print("[*] Please wait...")
time.sleep(1)
print("[*] Please wait...")
time.sleep(1)
print("[*] Please wait...")
time.sleep(1)
print("[*] Please wait...")
time.sleep(1)
print("[*] Please wait...")
time.sleep(1)
print("[*] Please wait...")
time.sleep(1)
print("[*] Please wait...")
time.sleep(1)
print("[*] Please wait...")
time.sleep(1)
print("[*] Please wait...")
time.sleep(1)
print("[*] Please wait...")
time.sleep(1)
print("[*] Please wait...")
time.sleep(1)
print("[*] Done 👍 ")
time.sleep(3)
print()
print()
print()
print("\033[96m      **MENU FPS** ")
print()
print()
print()
print()
print("  ___________________")
print("  |   [*] 120 FPS  |")
print()
print()
print("  |   [*] 90  FPS  |")
print()
print()
print("  |   [*] 60  FPS  |")
print("  __________________")
print()
print()
print()
input("\033[0mSelect The better Fps : ")
time.sleep(1)
print("\033[96m[*] Downloading (15mb size)... ")
time.sleep(1)
print("[*] Please wait a few seconds...")
time.sleep(5)
print()
print("[*] Success download")
time.sleep(1)
print("[*] Your phone set now in SMOOTH MODE-_-")
time.sleep(2)
print()
print("3")
time.sleep(1)
print("2")
time.sleep(1)
print("1")
time.sleep(3)
print("\033[91m[*] Please Reboot Your device")


